version: '3.8'

services:
  snmp-monitor:
    build: .
    container_name: snmp_trap_monitor
    ports:
      - "8081:8081"      # Flask 웹 UI
      - "162:162/udp"    # SNMP Trap UDP 포트
    volumes:
      - ./logs:/app/logs   # 로그 저장용 (필요 시)
    restart: unless-stopped
